config/routes.rb
Ianphoto::Application.routes.draw do
  resources :photos
  resources :categories

  match '/:slug.html' => 'static_pages#show', :as => :static_page

  namespace :admin do
    resources :photos do
      collection do
        get :bulk_edit
        put :bulk_update
      end
    end
    resources :categories do
      collection do
        put :arrange
      end
    end
    resources :static_pages do
      collection do
        put :arrange
      end
    end
    root :to => 'main#index'
  end

  root :to => 'main#index'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :category
  has_attached_file :picture, :styles => {:small => "200x200>", :processed => ""}, :processors => [:cropper]
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :crop_x2, :crop_y2, :crop_needed, :reset_cropping
  after_update :reprocess_picture, :if => :cropping_attributes_supplied?

  validates_presence_of :name
  validates_presence_of :category_id
  validates_attachment_presence :picture
  validates_attachment_content_type :picture, :content_type => ['image/jpeg', 'image/png', 'image/gif']
  validate :only_three_types_of_alignment_shall_stand

  named_scope :shuffled, :order => "rand()"
  named_scope :for_front_page, {:conditions => {:promote_to_front_page => true}}
  named_scope :from_category, lambda {|category| {:conditions => {:category_id => category.to_i}}}

  default_scope :order => "photos.position ASC"

  def to_i
    id
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end

  def self.to_json_collection(options = nil, &block)
    options ||= {}
    current_id = options.fetch(:current, 0).to_i
    current_index = incrementoid = 0
    pure_data = scoped({}).map {|photo|
      parameters = [:id, :name, :description, [:picture, :processed], [:picture, :small], :alignment].map do |parameter|
        [Array.wrap(parameter).reverse.join("_"), photo.send(*Array.wrap(parameter))]
      end
      current_index = incrementoid if current_id == photo.id
      incrementoid+=1
      Hash[*parameters.flatten].symbolize_keys
    }
    if block_given?
      pure_data.each(&block)
    end
    {:items => pure_data, :start => options.fetch(:start_index, current_index)}.to_json
  end

  def self.set_order_on!(photo_ids, options = nil)
    options ||= {}
    starting_with = options.fetch(:staring_with, 1).to_i.pred
    photo_ids.each do |photo_id|
      Photo.update_all({:position => (starting_with = starting_with.next)}, {:id => photo_id})
    end
  end

  def cropping_attributes_supplied?
    return false if crop_needed == "false" && reset_cropping != "1"
    return false if crop_w.to_i == 0 || crop_h.to_i == 0
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def alignment
    vertical_alignment.blank? ? "center" : vertical_alignment.to_s
  end

  private
    def reprocess_picture
      picture.reprocess!
    end

    def only_three_types_of_alignment_shall_stand
      if vertical_alignment? && !["center", "top", "bottom"].include?(vertical_alignment.to_s)
        errors.add(:vertical_alignment, "should be top, center or bottom")
        return false
      end
      true
    end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController
  def new
    @photo = Photo.new
    @category_id = params[:category_id]
    if @category_id
      @category = Category.find(@category_id)
    end
  end

  def create
    @photo = Photo.new(params[:photo])
    if @photo.save
      Photo.set_order_on!(@photo.category.photo_ids)
      redirect_to admin_category_path(@photo.category_id)
    else
      render "new"
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html {redirect_to admin_category_path(@photo.category_id)}
        format.js {head :ok}
      else
        format.html{render "edit"}
        format.js {head :ok}
      end
    end
  end
  
  def bulk_edit
    @category = Category.find(params[:category_id])
    @destroy_category = params.fetch(:to_destroy, false)
    @other_categories = Category.all - [@category]
  end

  def bulk_update
    @category = Category.find(params[:category_id])
    case
      when params[:move_to] && @destination_category_id = params[:move_to].fetch(:category_id, false)
        @category.photos.update_all(:category_id => @destination_category_id)
      when params.fetch(:destroy_all, false)
        @category.photos.destroy_all
    end
    if params.fetch(:destroy_category, false)
      @category.destroy
      redirect_to admin_categories_path
    else
      redirect_to admin_category_path(@category)
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @category_id = @photo.category_id
    @photo.destroy
    redirect_to admin_category_path(@category_id)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    redirect_to :root
  end

  def show
    @photo = Photo.find(params[:id])
    @json_collection = Photo.from_category(@photo.category_id).to_json_collection(:current => @photo) do |photo|
      photo[:path] = photo_path(photo[:id])
    end
    @static_pages = StaticPage.all
  end

end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/admin/photos/_form.html.haml
-photo ||= @photo
-category_id ||= @category_id
=form_for [:admin, photo], :html => {:multipart => true} do |f|
  =error_messages_for photo
  -unless category_id
    %p
      =f.label :category_id
      =f.collection_select :category_id, Category.all, :id, :name
  -else
    =f.hidden_field :category_id, :value => category_id
  %p
    =f.label :name
    %br/
    =f.text_field :name
  %p
    =f.label :description
    %br/
    =f.text_area :description, :size => "60x5"
  %p
    =f.label :picture, "Picture #{"(only if you want to upload new)" unless f.object.new_record?}"
    %br/
    =f.file_field :picture
  %p
    =f.check_box :promote_to_front_page
    =f.label :promote_to_front_page
  %p
    =f.submit

app/views/admin/photos/bulk_edit.html.haml
%h2 
  Move or delete photos in category
  %em=@category

-if @destroy_category
  %h3 Category will be destroyed then

-if @other_categories.present?
  =form_tag bulk_update_admin_photos_path, :method => :put do
    =hidden_field_tag :category_id, @category.id
    =label_tag :move_to_category_id, "Move to category:"
    =collection_select :move_to, :category_id, @other_categories, :id, :name
    =hidden_field_tag :destroy_category, true if @destroy_category
    =submit_tag "Proceed"
-else
  %p
    You don't have any other categories to move photos from this category.
    =link_to "Create new category", new_admin_category_path

%p
  %strong OR

=form_tag bulk_update_admin_photos_path, :method => :put do
  =hidden_field_tag :category_id, @category.id
  =hidden_field_tag :destroy_all, true
  =label_tag "Delete all photos (forever!)"
  =hidden_field_tag :destroy_category, true if @destroy_category
  =submit_tag "Oh noes!", :confirm => "Are you sure?"

%p
  %strong OR

%p=link_to "Just get back and browse this category", admin_category_path(@category)

app/views/admin/photos/edit.html.haml
%h2 Editing photo

=render "form"

app/views/admin/photos/index.html.haml
<h1>Admin::Photos#index</h1>
<p>Find me in app/views/admin/photos/index.html.erb</p>

app/views/admin/photos/new.html.haml
%h2
  Uploading new photo
  -if @category
    %small (or back to #{link_to @category, admin_category_path(@category)})
=render "form"

app/views/admin/photos/show.html.haml
=javascript_include_tag "jcrop"
=javascript_include_tag "crop_image"
=stylesheet_link_tag "jcrop"
%h2 Cropping image
%p Drag and drop and then click Crop. Mind that real picture is 4 times bigger.
=image_tag @photo.picture(:original), :class => :croppable
=form_for [:admin, @photo] do |f|
  -%w(x y w h x2 y2).each do |attr|
    =f.hidden_field "crop_#{attr}", :id => "crop_#{attr}"
  =f.hidden_field :crop_needed, :id => "crop_needed"
  %p This is uncropped version of an image. Existing cropped version will not change if you submit this page not moving cropping edges. Unless you check this:
  %p
    =f.check_box :reset_cropping
    =f.label :reset_cropping, "I want full image again"
  %p in which case cropping will be forced to occur and you will get your image back like nothing ever happened
  %h3 Choose the way this picture should be aligned when browser window is resized
  %div{:class => "alignment_preview #{@photo.alignment}"}
    =image_tag @photo.picture(:small)
    .border
  -["top", "center", "bottom"].each do |alignment_type|
    %p
      =f.radio_button :vertical_alignment, alignment_type, :class => :vertical_alignment, :checked => alignment_type.eql?(@photo.alignment)
      =f.label :vertical_alignment, alignment_type.humanize, :value => alignment_type
  .cl
  %p
    =f.submit "Crop"
    &nbsp;
    =link_to "Cancel", admin_category_path(@photo.category_id)
  %p Cropping requires a few seconds and may be finished after you are redirected back to category page. If you don't see thumbnail changed, refresh category page.