config/routes.rb
Ianphoto::Application.routes.draw do
  resources :photos
  resources :categories

  match '/:slug.html' => 'static_pages#show', :as => :static_page

  namespace :admin do
    resources :photos do
      collection do
        get :bulk_edit
        put :bulk_update
      end
    end
    resources :categories do
      collection do
        put :arrange
      end
    end
    resources :static_pages do
      collection do
        put :arrange
      end
    end
    root :to => 'main#index'
  end

  root :to => 'main#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates_presence_of :name
  has_many :photos

  default_scope :order => "categories.position ASC"

  def self.set_order_on!(ids, options = nil)
    options ||= {}
    starting_with = options.fetch(:staring_with, 1).to_i.pred
    ids.each do |id|
      Category.update_all({:position => (starting_with = starting_with.next)}, {:id => id})
    end
  end

  def to_s; name end
  def to_i; id end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @photos = @category.photos
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
    if @photo_ids = params[:category].fetch(:photo_ids, false)
      Photo.set_order_on!(@photo_ids)
    end
    respond_to do |format|
      if @category.save
        format.html { redirect_to admin_categories_path }
        format.js { head :ok }
      else
        format.html { render :edit }
        format.js { render :nothing }
      end
    end
  end

  def arrange
    respond_to do |format|
      if @category_ids = params[:categories].fetch(:category_id, nil)
        Category.set_order_on!(@category_ids)
        format.js { head :ok }
      else
        format.js { render :nothing }
      end
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.photos.exists?
      return redirect_to bulk_edit_admin_photos_path(:category_id => @category.id, :to_destroy => :true)
    else
      @category.destroy
      redirect_to admin_categories_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    if @category.photos.present?
      redirect_to @category.photos.first
    else
      redirect_to :root
    end
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_form.html.haml
-category ||= @category
=form_for [:admin, category] do |f|
  =error_messages_for category
  %label{:for => :name} Category name:
  =f.text_field :name
  =f.submit "Save"

app/views/admin/categories/edit.html.haml
%h2
  Edit category 
  %small (or get back to #{link_to "categories index", admin_categories_path})
=render "form"

app/views/admin/categories/index.html.haml
:javascript
  $(document).ready(function() {
    $(".edit_form").hide();
    $("ul.categories").sortable({
      stop: function(ev, ui) {
        $("#arrange_categories_form").ajaxSubmit();
      }
    });
  });

-if @categories.blank?
  %h2 No categories exist
-else
  %h2 Manage categories
  %p Categories will apear in menu in this exact order. Drag them to rearrange.
  =form_tag arrange_admin_categories_path, :id => "arrange_categories_form", :method => :put do
    %ul.categories
      -@categories.each do |category|
        %li.m-10
          =hidden_field_tag "categories[category_id][]", category.id
          =link_to category, admin_category_path(category)
          (#{link_to "Edit", edit_admin_category_path(category), :class => :edit} | #{link_to "Remove", admin_category_path(category), :method => :delete, :confirm => "Are you sure?"})

%h2 Add new category
=render "admin/categories/form"

app/views/admin/categories/new.html.haml
%h2
  Add new category
  %small (or get back to #{link_to "categories index", admin_categories_path})
=render "form"

app/views/admin/categories/show.html.haml
:javascript
  $(document).ready(function() {
    $("ul.photos").sortable({
      stop: function(ev, ui) {
        $("#sorting_form").ajaxSubmit();
      }
    });
    $("input.promote_to_front_page").click(function() {
      $.post($(this).attr("data-submit-to"), {
        "photo[promote_to_front_page]": ($(this).is(":checked") ? 1 : 0),
        "authenticity_token": "#{form_authenticity_token}",
        "_method": "put"
      });
    });
  });

%h2
  Managing photos in
  %em=@category
%p
  =link_to "&larr; Back to categories index".html_safe, admin_categories_path
  |
  %strong=link_to "Upload new photo", new_admin_photo_path(:category_id => @category.id)
  |
  =link_to "Edit category", edit_admin_category_path(@category)
  |
  =link_to "Move or destroy all photos", bulk_edit_admin_photos_path(:category_id => @category.id)
  |
  =link_to "Delete this category", admin_category_path(@category), :method => :delete, :confirm => "Are you sure?"

%br/

-if @category.photos.blank?
  %h3 This category is empty
-else
  %h3 Photos will appear in this exact order. Drag them to rearrange. Photos on front page appear in random order.

=form_for [:admin, @category], :url => admin_category_path(:format => :js), :html => {:method => :put, :id => "sorting_form"} do |f|
  %ul.photos.inline-blocks
    -@category.photos.each do |photo|
      %li.bordered
        =hidden_field_tag "category[photo_ids][]", photo.id
        %h4=truncate photo.name
        %br/
        =image_tag photo.picture(:small)
        %br/
        %br/
        =link_to "show", photo_path(photo)
        |
        =link_to "crop", admin_photo_path(photo)
        |
        =link_to "edit", edit_admin_photo_path(photo)
        |
        =link_to "delete", admin_photo_path(photo), :method => :delete, :confirm => "Are you sure?"
        %br/
        =check_box_tag :promote_to_front_page, 1, photo.promote_to_front_page, :id => "promote_to_front_page_#{photo.id}", :class => "promote_to_front_page", :"data-submit-to" => admin_photo_path(photo, :format => :js)
        =label_tag :promote_to_front_page, "front page", :for => "promote_to_front_page_#{photo.id}"