config/routes.rb
Ianphoto::Application.routes.draw do
  resources :photos
  resources :categories

  match '/:slug.html' => 'static_pages#show', :as => :static_page

  namespace :admin do
    resources :photos do
      collection do
        get :bulk_edit
        put :bulk_update
      end
    end
    resources :categories do
      collection do
        put :arrange
      end
    end
    resources :static_pages do
      collection do
        put :arrange
      end
    end
    root :to => 'main#index'
  end

  root :to => 'main#index'
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :body
  validates_presence_of :slug
  validates_uniqueness_of :slug
  
  before_save :parameterize_slug

  default_scope :order => "static_pages.position ASC"

  def self.set_order_on!(ids, options = nil)
    options ||= {}
    starting_with = options.fetch(:staring_with, 1).to_i.pred
    ids.each do |id|
      StaticPage.update_all({:position => (starting_with = starting_with.next)}, {:id => id})
    end
  end

  def to_s
    name
  end

  private
    def parameterize_slug
      self.slug = self.slug.parameterize.underscore
    end
end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < ApplicationController
  def index
    @static_pages = StaticPage.all
  end

  def new
    @static_page = StaticPage.new
  end

  def create
    @static_page = StaticPage.new(params[:static_page])
    if @static_page.save
      redirect_to admin_static_pages_path
    else
      render :new
    end
  end

  def edit
    @static_page = StaticPage.find(params[:id])
  end

  def update
    @static_page = StaticPage.find(params[:id])
    if @static_page.update_attributes(params[:static_page])
      redirect_to admin_static_pages_path
    else
      render :edit
    end
  end

  def destroy
    @static_page = StaticPage.find(params[:id])
    @static_page.destroy
    redirect_to admin_static_pages_path
  end

  def arrange
    respond_to do |format|
      if @static_page_ids = params[:static_pages].fetch(:static_page_id, nil)
        StaticPage.set_order_on!(@static_page_ids)
        format.js { head :ok }
      else
        format.js { render :nothing }
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    @static_page = StaticPage.find_by_slug(params[:slug])
    respond_to do |format|
      format.html { @photo = Photo.shuffled.first }
      format.js {render :partial => "static_pages/content"}
    end
  end

end

app/helpers/admin/static_pages_helper.rb
module Admin::StaticPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/static_pages/_form.html.haml
=form_for [:admin, @static_page] do |f|
  =error_messages_for @static_page
  %p
    =f.label :name
    =f.text_field :name
  %p
    =f.label :slug
    =f.text_field :slug
  %p
    =f.label :body
    (Use 
    =link_to "textile markup", "http://warpedvisions.org/projects/textile-cheat-sheet/", :target => :_blank
    )
  %p
    =f.text_area :body, :size => "100x30"
  %p
    =f.submit "Save"

app/views/admin/static_pages/create.html.haml
<h1>Admin::StaticPages#create</h1>
<p>Find me in app/views/admin/static_pages/create.html.erb</p>

app/views/admin/static_pages/destroy.html.haml
<h1>Admin::StaticPages#destroy</h1>
<p>Find me in app/views/admin/static_pages/destroy.html.erb</p>

app/views/admin/static_pages/edit.html.haml
%h2 Editing static page

=render "form"

app/views/admin/static_pages/index.html.haml
:javascript
  $(document).ready(function() {
    $("ul.static_pages").sortable({
      stop: function(ev, ui) {
        $("#arrange_static_pages_form").ajaxSubmit();
      }
    });
  });

-if @static_pages.blank?
  %h2 No static pages exist
  =link_to "Create first static page", new_admin_static_page_path
-else
  %h2 Manage static pages
  =link_to "Add static page", new_admin_static_page_path
  =form_tag arrange_admin_static_pages_path, :id => "arrange_static_pages_form", :method => :put do
    %ul.static_pages
      -@static_pages.each do |static_page|
        %li.m-10
          =hidden_field_tag "static_pages[static_page_id]", static_page.id
          =link_to static_page, static_page_path(static_page)
          (
          =link_to "Edit", edit_admin_static_page_path(static_page)
          |
          =link_to "Remove", admin_static_page_path(static_page), :method => :delete, :confirm => "Are you sure?"
          )

app/views/admin/static_pages/new.html.haml
%h2 Creating static page

=render "form"

app/views/admin/static_pages/update.html.haml
<h1>Admin::StaticPages#update</h1>
<p>Find me in app/views/admin/static_pages/update.html.erb</p>